# Generated by Django 3.0.4 on 2020-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Content', models.CharField(max_length=300)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
