# Generated by Django 3.0.4 on 2020-03-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Author', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
                ('TimeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
