# Generated by Django 3.0.4 on 2020-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogApp', '0004_auto_20200420_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='S_No',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
