# Generated by Django 3.0.4 on 2020-04-20 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('TimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('BlogPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlogApp.Post')),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBlogApp.BlogComment')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
