# Generated by Django 3.0.4 on 2020-04-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogApp', '0002_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
